version: '3.8'

services:
  # FastAPI Backend
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valids-api
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - DATABASE_NAME=valids_db
      - API_V1_PREFIX=/api/v1
      - PROJECT_NAME=ValidS API
      - DEBUG=True
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    depends_on:
      - mongo
    networks:
      - valids-network
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: valids-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=valids_db
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - valids-network
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Mongo Express (Optional - MongoDB Web UI)
  mongo-express:
    image: mongo-express:latest
    container_name: valids-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
    networks:
      - valids-network
    restart: unless-stopped

networks:
  valids-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

